var userData = {
  'login': 'pataruco',
  'id': 10330222,
  'avatar_url': 'https://avatars.githubusercontent.com/u/10330222?v=3',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/pataruco',
  'html_url': 'https://github.com/pataruco',
  'followers_url': 'https://api.github.com/users/pataruco/followers',
  'following_url': 'https://api.github.com/users/pataruco/following{/other_user}',
  'gists_url': 'https://api.github.com/users/pataruco/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/pataruco/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/pataruco/subscriptions',
  'organizations_url': 'https://api.github.com/users/pataruco/orgs',
  'repos_url': 'https://api.github.com/users/pataruco/repos',
  'events_url': 'https://api.github.com/users/pataruco/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/pataruco/received_events',
  'type': 'User',
  'site_admin': false,
  'name': 'Pedro Martin',
  'company': null,
  'blog': null,
  'location': 'United Kingdom',
  'email': 'pataruco@gmail.com',
  'hireable': true,
  'bio': null,
  'public_repos': 28,
  'public_gists': 5,
  'followers': 11,
  'following': 3,
  'created_at': '2014-12-28T12:37:03Z',
  'updated_at': '2016-04-06T21:42:40Z'
}

module.exports = userData
